import turtle

pen = turtle.Turtle()
turtle.title('sxifah wd')
pen.pensize(5)
pen.pencolor('black')


pen.fillcolor('red')
pen.begin_fill()
pen.forward(100)
pen.left(90)
pen.forward(100)
pen.left(90)
pen.forward(100)
pen.left(90)
pen.forward(100)
pen.left(90)
pen.end_fill()

pen.penup()
pen.goto(100 , 100)
pen.down()
pen.fillcolor('blue')
pen.begin_fill()
pen.forward(100)
pen.left(90)
pen.forward(100)
pen.left(90)
pen.forward(100)
pen.left(90)
pen.forward(100)
pen.left(90)
pen.end_fill()

pen.penup()
pen.goto(200 , 100)
pen.down()
pen.fillcolor('yellow')
pen.begin_fill()
pen.forward(100)
pen.right(90)
pen.forward(100)
pen.right(90)
pen.forward(100)
pen.right(90)
pen.forward(100)
pen.right(90)
pen.end_fill()